#!/bin/bash

if [ "$SLURM_LOCALID" -gt 23 ]; then
    export ROCR_VISIBLE_DEVICES=$((SLURM_LOCALID - 24))
elif [ "$SLURM_LOCALID" -gt 15 ]; then
    export ROCR_VISIBLE_DEVICES=$((SLURM_LOCALID - 16))
elif [ "$SLURM_LOCALID" -gt 7 ]; then
    export ROCR_VISIBLE_DEVICES=$((SLURM_LOCALID - 8))
else
    export ROCR_VISIBLE_DEVICES=$SLURM_LOCALID
fi

exec $*
